### ISSUE TITLE
Web Build Error 'TypeError: Cannot read properties of undefined (reading: 'init'), null, null)

### ISSUE THREAD

**Issue by mikhael28** [GetDutchie/datadog_flutter#81]
Hey everyone, I am loving this unofficially official flutter SDK for Datadog. The Android and iOS builds work very smoothly, but I am having an issue with the web build/deployment that I was wondering if someone can help me with/identity the issue.

When running the Chrome development server, I am getting this data in the Chrome console:
```Installed new service worker.
VM473:1 This app is linked to the debug service: ws://127.0.0.1:55452/nO3G8J4sP-4=/ws
errors.dart:251 Uncaught (in promise) Error: PlatformException(error, TypeError: Cannot read properties of undefined (reading 'init'), null, null)
    at Object.throw_ [as throw] (errors.dart:251:49)
    at StandardMethodCodec.decodeEnvelope (message_codecs.dart:607:7)
    at MethodChannel._invokeMethod (platform_channel.dart:177:18)
    at _invokeMethod.next (<anonymous>)
    at async_patch.dart:45:50
    at _RootZone.runUnary (zone.dart:1685:54)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:159:18)
    at handleValueCallback (future_impl.dart:766:44)
    at Function._propagateToListeners (future_impl.dart:795:13)
    at _Future.new.[_completeWithValue] (future_impl.dart:601:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:639:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:166:15```

There are no failing network requests, meaning all files are being fetched - seems to be limited to compilation error.

Now, when trying to run a production build and generate a `main.dart.js` bundle, I get a slightly more helpful error:
```(index):91 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):91
main.dart.js:3296 Uncaught PlatformException(error, ReferenceError: DD_LOGS is not defined, null, null)
    at Object.c (https://cedarai.github.io/flutter-mobile/main.dart.js:3296:3)
    at ab6.DB (https://cedarai.github.io/flutter-mobile/main.dart.js:60273:14)
    at https://cedarai.github.io/flutter-mobile/main.dart.js:60346:98
    at anJ.a (https://cedarai.github.io/flutter-mobile/main.dart.js:4486:62)
    at anJ.$2 (https://cedarai.github.io/flutter-mobile/main.dart.js:33181:14)
    at amK.$1 (https://cedarai.github.io/flutter-mobile/main.dart.js:33175:21)
    at SW.kA (https://cedarai.github.io/flutter-mobile/main.dart.js:34133:32)
    at age.$0 (https://cedarai.github.io/flutter-mobile/main.dart.js:33546:11)
    at Object.uq (https://cedarai.github.io/flutter-mobile/main.dart.js:4576:40)
    at a5.ql (https://cedarai.github.io/flutter-mobile/main.dart.js:33478:3)```

Any idea what might be going on? I've tried digging into the main.dart.js, but the minified code isn't giving me much. I can post it later if you can't think of anything.

**Comment by mikhael28** [comment]
My Flutter dependencies:
```dependencies:
  flutter:
    sdk: flutter
  google_fonts: 2.1.1
  provider: ^6.0.0
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  amazon_cognito_identity_dart_2: ^1.0.5
  flutter_dotenv: ^5.0.2
  jiffy: ^5.0.0
  modal_bottom_sheet: ^2.0.0
  collection: ^1.15.0
  byte_flow: ^1.0.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  scrollable_positioned_list: ^0.2.3
  scroll_to_index: ^2.1.1
  sticky_headers: ^0.2.0
  datadog_flutter: ^1.5.2
  connectivity_plus: ^2.2.1
  flutter_easyloading: ^3.0.3
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  dart_code_metrics: ^4.11.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter```

**Comment by mikhael28** [comment]
And a clean bill of health from flutter doctor
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!```

**Comment by mikhael28** [comment]
When I comment out all import statements and Datadog initialization, everything works just fine. Again, iOS and Android work well.

**Comment by mikhael28** [comment]
I am silly - this information resolved my issue. Mostly. Found another bug, going to post now. https://github.com/GetDutchie/datadog_flutter/blob/main/example/web/index.html
